import { NextRequest, NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

export async function POST(request: NextRequest) {
  try {
    const { preferences, recommendations, itinerary } = await request.json();

    // Create PDF document
    const doc = new jsPDF();
    
    // Set up document
    doc.setFontSize(20);
    doc.text('TravelMind - AI Travel Itinerary', 20, 30);
    
    // Travel Summary
    doc.setFontSize(16);
    doc.text('Travel Summary', 20, 50);
    doc.setFontSize(12);
    doc.text(`Destination: ${preferences.destination}`, 20, 65);
    doc.text(`Budget: ${preferences.budget}`, 20, 75);
    doc.text(`Dates: ${preferences.startDate} - ${preferences.endDate}`, 20, 85);
    doc.text(`Travelers: ${preferences.travelers}`, 20, 95);
    doc.text(`Interests: ${preferences.interests}`, 20, 105);

    // Recommendations
    doc.setFontSize(16);
    doc.text('AI Recommendations', 20, 125);
    doc.setFontSize(12);
    
    let yPosition = 140;
    if (recommendations && recommendations.length > 0) {
      recommendations.forEach((rec: any, index: number) => {
        doc.text(`${index + 1}. ${rec.city}`, 20, yPosition);
        doc.text(`   Rating: ${rec.rating}/5`, 25, yPosition + 10);
        doc.text(`   Budget: ${rec.budget}`, 25, yPosition + 20);
        doc.text(`   Best for: ${rec.bestFor}`, 25, yPosition + 30);
        yPosition += 50;
      });
    }

    // Itinerary Details
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(16);
    doc.text('Detailed Itinerary', 20, yPosition);
    yPosition += 20;

    // Mock detailed itinerary
    const mockSchedule = [
      {
        day: 1,
        title: "Arrival & Gothic Quarter",
        activities: [
          { time: "10:00", activity: "Arrive at Barcelona Airport" },
          { time: "12:00", activity: "Check into Hotel" },
          { time: "14:00", activity: "Gothic Quarter Walking Tour" },
          { time: "19:00", activity: "Dinner at Cal Pep" }
        ]
      },
      {
        day: 2,
        title: "Gaudí's Masterpieces",
        activities: [
          { time: "09:00", activity: "Sagrada Familia Visit" },
          { time: "11:30", activity: "Park Güell Exploration" },
          { time: "14:00", activity: "Lunch at Granja M. Viader" },
          { time: "16:00", activity: "Casa Batlló Tour" }
        ]
      }
    ];

    doc.setFontSize(12);
    mockSchedule.forEach((day) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      
      doc.setFontSize(14);
      doc.text(`Day ${day.day}: ${day.title}`, 20, yPosition);
      yPosition += 15;
      
      doc.setFontSize(10);
      day.activities.forEach((activity) => {
        doc.text(`${activity.time} - ${activity.activity}`, 25, yPosition);
        yPosition += 10;
      });
      yPosition += 10;
    });

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Generated by TravelMind AI - Page ${i} of ${pageCount}`, 20, 285);
    }

    // Generate PDF as buffer
    const pdfBuffer = doc.output('arraybuffer');
    
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="travel-itinerary.pdf"',
      },
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}